### ISSUE TITLE
Fix potential NULL pointer dereference

### ISSUE THREAD

**Issue by msekletar** [redhat-plumbers/systemd-rhel7#136]
Recently we have merged https://github.com/redhat-plumbers/systemd-rhel7/pull/135 with the backport of https://github.com/redhat-plumbers/systemd-rhel7/commit/43b4e3058c106e663bbd5413e7bd106e55d6fd79. In the upstream code we now have following block of code,
```C
suffix = strrchr(de->d_name, '.');
if (!STRPTR_IN_SET(suffix, ".wants", ".requires"))
        continue;
```

Because in our RHEL-7 version we are missing `STRPTR_IN_SET()` macro the code got rewritten as follows,

```C
suffix = strrchr(de->d_name, '.');
if (!streq(suffix, ".wants") && !streq(suffix, ".requires"))
        continue;
```
However, above piece of code has a bug. In case that `de->d_name` doesn't contain `.` then`streq()` macro, which in turn calls `strcmp()` function, will pass `NULL` as first argument and that will cause a crash. We should fix this and replace calls to `streq()` with `streq_ptr()`.

**Comment by jamacku** [comment]
@dtardon This is issue in upstream as well

**Comment by jamacku** [comment]
Never mind, I didn't notice what michal had written about ``STRPTR_IN_SET()``.
